server:
  port: 8204

spring:
  application:
    name: mall-gl-search
  cloud:
    loadbalancer:
      enabled: true
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://127.0.0.1:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
